class PostFail1 {
    var a:Int := 5

    method test1(a:Int) {
        if true
            self.a := a
    }
    @post(self.a = a)
    
    method test2(a:Int) {
        self.a += 1
    }
    @post(self.a = @pre(self.a) + 2)
    
    @class
    method main() {
        var p := PostFail1()
        p.test1(10)
        try {
            p.test2(10)
            Console.writeLine(p.a)
        }
        catch e:AssertionError {
            Console.writeLine("success")
        }
    }
}